# Generated by Django 4.2 on 2023-06-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
