# Generated by Django 4.2 on 2023-05-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_category_cooker_meal_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cooker',
            new_name='Cook',
        ),
    ]
