# Generated by Django 4.2 on 2023-06-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_time',
            field=models.DateTimeField(default='2023-06-28 18:50'),
            preserve_default=False,
        ),
    ]
