# Generated by Django 4.2 on 2023-06-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_reservation_date_remove_reservation_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date_time']},
        ),
    ]
