# Generated by Django 4.2 on 2023-07-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_time',
            field=models.DateTimeField(help_text='Date and time when the guest arrives.'),
        ),
    ]
